var jsonData = {
    "Import": [
        {
            "GoodsName": "Live animals",
            "Mexico": "y",
            "Ukraine": "y",
            "South Africa": "y",
            "Denmark": "y",
            "Austria": "y",
            "Congo, The Democratic Republic": "n",
            "Greece": "n",
            "Kuwait": "y",
            "Pakistan": "y",
            "Finland": "y",
            "Romania": "y",
            "Bangladesh": "y",
            "Czech Republic": "y",
            "New Zealand": "y",
            "Sudan": "y",
            "Hungary": "y",
            "Syria": "y",
            "Bulgaria": "y",
            "Norway": "y",
            "Ethiopia": "y",
            "Yemen": "y",
            "Slovakia": "n"
        },
        {
            "GoodsName": "Plant products",
            "Mexico": "y",
            "Ukraine": "y",
            "South Africa": "y",
            "Denmark": "y",
            "Austria": "n",
            "Congo, The Democratic Republic": "n",
            "Greece": "y",
            "Kuwait": "y",
            "Pakistan": "y",
            "Finland": "n",
            "Romania": "y",
            "Bangladesh": "y",
            "Czech Republic": "y",
            "New Zealand": "y",
            "Sudan": "y",
            "Hungary": "y",
            "Syria": "y",
            "Bulgaria": "y",
            "Norway": "n",
            "Ethiopia": "y",
            "Yemen": "y",
            "Slovakia": "n"
        },
        {
            "GoodsName": "Vegetable products",
            "Mexico": "n",
            "Ukraine": "y",
            "South Africa": "n",
            "Denmark": "n",
            "Austria": "n",
            "Congo, The Democratic Republic": "n",
            "Greece": "n",
            "Kuwait": "n",
            "Pakistan": "n",
            "Finland": "n",
            "Romania": "n",
            "Bangladesh": "y",
            "Czech Republic": "n",
            "New Zealand": "y",
            "Sudan": "n",
            "Hungary": "n",
            "Syria": "y",
            "Bulgaria": "y",
            "Norway": "n",
            "Ethiopia": "n",
            "Yemen": "y",
            "Slovakia": "n"
        },
        {
            "GoodsName": "Prepared Foodstuffs",
            "Mexico": "y",
            "Ukraine": "y",
            "South Africa": "y",
            "Denmark": "y",
            "Austria": "y",
            "Congo, The Democratic Republic": "n",
            "Greece": "y",
            "Kuwait": "y",
            "Pakistan": "y",
            "Finland": "n",
            "Romania": "n",
            "Bangladesh": "y",
            "Czech Republic": "y",
            "New Zealand": "y",
            "Sudan": "y",
            "Hungary": "y",
            "Syria": "y",
            "Bulgaria": "y",
            "Norway": "y",
            "Ethiopia": "n",
            "Yemen": "y",
            "Slovakia": "y"
        },
        {
            "GoodsName": "Mineral products",
            "Mexico": "n",
            "Ukraine": "y",
            "South Africa": "y",
            "Denmark": "n",
            "Austria": "y",
            "Congo, The Democratic Republic": "n",
            "Greece": "y",
            "Kuwait": "y",
            "Pakistan": "y",
            "Finland": "n",
            "Romania": "n",
            "Bangladesh": "n",
            "Czech Republic": "n",
            "New Zealand": "n",
            "Sudan": "n",
            "Hungary": "n",
            "Syria": "n",
            "Bulgaria": "y",
            "Norway": "n",
            "Ethiopia": "n",
            "Yemen": "n",
            "Slovakia": "n"
        },
        {
            "GoodsName": "Chemical Products",
            "Mexico": "y",
            "Ukraine": "n",
            "South Africa": "y",
            "Denmark": "y",
            "Austria": "y",
            "Congo, The Democratic Republic": "n",
            "Greece": "y",
            "Kuwait": "y",
            "Pakistan": "y",
            "Finland": "y",
            "Romania": "y",
            "Bangladesh": "n",
            "Czech Republic": "y",
            "New Zealand": "y",
            "Sudan": "n",
            "Hungary": "y",
            "Syria": "n",
            "Bulgaria": "y",
            "Norway": "y",
            "Ethiopia": "n",
            "Yemen": "n",
            "Slovakia": "y"
        },
        {
            "GoodsName": "Plastics",
            "Mexico": "y",
            "Ukraine": "n",
            "South Africa": "y",
            "Denmark": "y",
            "Austria": "y",
            "Congo, The Democratic Republic": "n",
            "Greece": "y",
            "Kuwait": "y",
            "Pakistan": "n",
            "Finland": "y",
            "Romania": "y",
            "Bangladesh": "n",
            "Czech Republic": "y",
            "New Zealand": "n",
            "Sudan": "n",
            "Hungary": "y",
            "Syria": "n",
            "Bulgaria": "y",
            "Norway": "y",
            "Ethiopia": "n",
            "Yemen": "n",
            "Slovakia": "y"
        },
        {
            "GoodsName": "Raw Hide",
            "Mexico": "n",
            "Ukraine": "n",
            "South Africa": "n",
            "Denmark": "n",
            "Austria": "n",
            "Congo, The Democratic Republic": "n",
            "Greece": "n",
            "Kuwait": "n",
            "Pakistan": "y",
            "Finland": "n",
            "Romania": "n",
            "Bangladesh": "n",
            "Czech Republic": "n",
            "New Zealand": "n",
            "Sudan": "n",
            "Hungary": "n",
            "Syria": "n",
            "Bulgaria": "n",
            "Norway": "n",
            "Ethiopia": "n",
            "Yemen": "n",
            "Slovakia": "n"
        },
        {
            "GoodsName": "Wood",
            "Mexico": "y",
            "Ukraine": "y",
            "South Africa": "y",
            "Denmark": "n",
            "Austria": "y",
            "Congo, The Democratic Republic": "n",
            "Greece": "n",
            "Kuwait": "n",
            "Pakistan": "n",
            "Finland": "y",
            "Romania": "y",
            "Bangladesh": "n",
            "Czech Republic": "n",
            "New Zealand": "y",
            "Sudan": "n",
            "Hungary": "n",
            "Syria": "n",
            "Bulgaria": "y",
            "Norway": "y",
            "Ethiopia": "n",
            "Yemen": "n",
            "Slovakia": "n"
        },
        {
            "GoodsName": "Paper",
            "Mexico": "n",
            "Ukraine": "n",
            "South Africa": "y",
            "Denmark": "n",
            "Austria": "y",
            "Congo, The Democratic Republic": "n",
            "Greece": "n",
            "Kuwait": "y",
            "Pakistan": "y",
            "Finland": "y",
            "Romania": "n",
            "Bangladesh": "n",
            "Czech Republic": "n",
            "New Zealand": "y",
            "Sudan": "n",
            "Hungary": "y",
            "Syria": "n",
            "Bulgaria": "n",
            "Norway": "n",
            "Ethiopia": "n",
            "Yemen": "n",
            "Slovakia": "n"
        },
        {
            "GoodsName": "Textiles",
            "Mexico": "y",
            "Ukraine": "n",
            "South Africa": "y",
            "Denmark": "y",
            "Austria": "n",
            "Congo, The Democratic Republic": "n",
            "Greece": "y",
            "Kuwait": "y",
            "Pakistan": "y",
            "Finland": "n",
            "Romania": "y",
            "Bangladesh": "y",
            "Czech Republic": "y",
            "New Zealand": "n",
            "Sudan": "n",
            "Hungary": "n",
            "Syria": "y",
            "Bulgaria": "y",
            "Norway": "n",
            "Ethiopia": "n",
            "Yemen": "n",
            "Slovakia": "n"
        },
        {
            "GoodsName": "Footwear",
            "Mexico": "n",
            "Ukraine": "n",
            "South Africa": "n",
            "Denmark": "n",
            "Austria": "n",
            "Congo, The Democratic Republic": "n",
            "Greece": "n",
            "Kuwait": "n",
            "Pakistan": "y",
            "Finland": "n",
            "Romania": "n",
            "Bangladesh": "y",
            "Czech Republic": "n",
            "New Zealand": "n",
            "Sudan": "n",
            "Hungary": "n",
            "Syria": "y",
            "Bulgaria": "n",
            "Norway": "n",
            "Ethiopia": "n",
            "Yemen": "n",
            "Slovakia": "n"
        },
        {
            "GoodsName": "Construction",
            "Mexico": "n",
            "Ukraine": "n",
            "South Africa": "n",
            "Denmark": "n",
            "Austria": "y",
            "Congo, The Democratic Republic": "n",
            "Greece": "y",
            "Kuwait": "y",
            "Pakistan": "y",
            "Finland": "n",
            "Romania": "n",
            "Bangladesh": "n",
            "Czech Republic": "y",
            "New Zealand": "n",
            "Sudan": "n",
            "Hungary": "n",
            "Syria": "y",
            "Bulgaria": "n",
            "Norway": "n",
            "Ethiopia": "n",
            "Yemen": "n",
            "Slovakia": "n"
        },
        {
            "GoodsName": "Jewelery",
            "Mexico": "n",
            "Ukraine": "n",
            "South Africa": "y",
            "Denmark": "n",
            "Austria": "y",
            "Congo, The Democratic Republic": "n",
            "Greece": "n",
            "Kuwait": "n",
            "Pakistan": "n",
            "Finland": "n",
            "Romania": "n",
            "Bangladesh": "n",
            "Czech Republic": "n",
            "New Zealand": "n",
            "Sudan": "n",
            "Hungary": "n",
            "Syria": "n",
            "Bulgaria": "n",
            "Norway": "n",
            "Ethiopia": "n",
            "Yemen": "n",
            "Slovakia": "n"
        },
        {
            "GoodsName": "Base metals",
            "Mexico": "y",
            "Ukraine": "y",
            "South Africa": "y",
            "Denmark": "y",
            "Austria": "y",
            "Congo, The Democratic Republic": "y",
            "Greece": "y",
            "Kuwait": "y",
            "Pakistan": "y",
            "Finland": "y",
            "Romania": "y",
            "Bangladesh": "n",
            "Czech Republic": "y",
            "New Zealand": "n",
            "Sudan": "n",
            "Hungary": "y",
            "Syria": "y",
            "Bulgaria": "y",
            "Norway": "y",
            "Ethiopia": "n",
            "Yemen": "n",
            "Slovakia": "n"
        },
        {
            "GoodsName": "Machine",
            "Mexico": "y",
            "Ukraine": "y",
            "South Africa": "y",
            "Denmark": "y",
            "Austria": "y",
            "Congo, The Democratic Republic": "n",
            "Greece": "y",
            "Kuwait": "y",
            "Pakistan": "y",
            "Finland": "y",
            "Romania": "y",
            "Bangladesh": "n",
            "Czech Republic": "y",
            "New Zealand": "y",
            "Sudan": "n",
            "Hungary": "y",
            "Syria": "n",
            "Bulgaria": "y",
            "Norway": "y",
            "Ethiopia": "n",
            "Yemen": "n",
            "Slovakia": "y"
        },
        {
            "GoodsName": "Transport Equipment",
            "Mexico": "y",
            "Ukraine": "y",
            "South Africa": "y",
            "Denmark": "y",
            "Austria": "y",
            "Congo, The Democratic Republic": "n",
            "Greece": "y",
            "Kuwait": "y",
            "Pakistan": "y",
            "Finland": "y",
            "Romania": "y",
            "Bangladesh": "n",
            "Czech Republic": "y",
            "New Zealand": "n",
            "Sudan": "n",
            "Hungary": "y",
            "Syria": "n",
            "Bulgaria": "n",
            "Norway": "y",
            "Ethiopia": "n",
            "Yemen": "y",
            "Slovakia": "y"
        },
        {
            "GoodsName": "Optical",
            "Mexico": "y",
            "Ukraine": "y",
            "South Africa": "y",
            "Denmark": "y",
            "Austria": "y",
            "Congo, The Democratic Republic": "n",
            "Greece": "n",
            "Kuwait": "n",
            "Pakistan": "y",
            "Finland": "y",
            "Romania": "y",
            "Bangladesh": "n",
            "Czech Republic": "y",
            "New Zealand": "y",
            "Sudan": "n",
            "Hungary": "y",
            "Syria": "n",
            "Bulgaria": "n",
            "Norway": "y",
            "Ethiopia": "n",
            "Yemen": "n",
            "Slovakia": "y"
        },
        {
            "GoodsName": "Ammunition",
            "Mexico": "n",
            "Ukraine": "n",
            "South Africa": "n",
            "Denmark": "n",
            "Austria": "n",
            "Congo, The Democratic Republic": "n",
            "Greece": "y",
            "Kuwait": "n",
            "Pakistan": "y",
            "Finland": "n",
            "Romania": "n",
            "Bangladesh": "n",
            "Czech Republic": "y",
            "New Zealand": "n",
            "Sudan": "n",
            "Hungary": "n",
            "Syria": "n",
            "Bulgaria": "y",
            "Norway": "n",
            "Ethiopia": "n",
            "Yemen": "n",
            "Slovakia": "n"
        },
        {
            "GoodsName": "Mfd items",
            "Mexico": "y",
            "Ukraine": "y",
            "South Africa": "n",
            "Denmark": "y",
            "Austria": "y",
            "Congo, The Democratic Republic": "n",
            "Greece": "y",
            "Kuwait": "y",
            "Pakistan": "y",
            "Finland": "y",
            "Romania": "y",
            "Bangladesh": "n",
            "Czech Republic": "y",
            "New Zealand": "n",
            "Sudan": "n",
            "Hungary": "y",
            "Syria": "n",
            "Bulgaria": "y",
            "Norway": "n",
            "Ethiopia": "n",
            "Yemen": "n",
            "Slovakia": "y"
        },
        {
            "GoodsName": "Arts",
            "Mexico": "n",
            "Ukraine": "n",
            "South Africa": "n",
            "Denmark": "n",
            "Austria": "n",
            "Congo, The Democratic Republic": "n",
            "Greece": "n",
            "Kuwait": "y",
            "Pakistan": "n",
            "Finland": "n",
            "Romania": "n",
            "Bangladesh": "n",
            "Czech Republic": "n",
            "New Zealand": "n",
            "Sudan": "n",
            "Hungary": "n",
            "Syria": "n",
            "Bulgaria": "n",
            "Norway": "n",
            "Ethiopia": "n",
            "Yemen": "n",
            "Slovakia": "n"
        }
    ],
    "Export": [
        {
            "GoodsName": "Live animals",
            "Togo": "n",
            "Germany": "n",
            "Portugal": "n",
            "Hong Kong": "n",
            "Brunei Darussalam": "n",
            "Tunisia": "n",
            "Sri Lanka": "n",
            "Mozambique": "n",
            "Bulgaria": "n",
            "New Zealand": "n",
            "Libya": "y",
            "Lebanon": "y",
            "Cote D'Ivoire": "n",
            "Ghana": "y",
            "Ukraine": "n",
            "Peru": "n",
            "Sweden": "n",
            "Gibraltar": "n",
            "Colombia": "n",
            "Argentina": "n",
            "Malta": "n",
            "Russia": "n"
        },
        {
            "GoodsName": "Plant products",
            "Togo": "n",
            "Germany": "y",
            "Portugal": "n",
            "Hong Kong": "n",
            "Brunei Darussalam": "n",
            "Tunisia": "n",
            "Sri Lanka": "n",
            "Mozambique": "n",
            "Bulgaria": "n",
            "New Zealand": "n",
            "Libya": "n",
            "Lebanon": "y",
            "Cote D'Ivoire": "n",
            "Ghana": "n",
            "Ukraine": "n",
            "Peru": "n",
            "Sweden": "n",
            "Gibraltar": "n",
            "Colombia": "n",
            "Argentina": "n",
            "Malta": "n",
            "Russia": "n"
        },
        {
            "GoodsName": "Vegetable products",
            "Togo": "n",
            "Germany": "n",
            "Portugal": "n",
            "Hong Kong": "n",
            "Brunei Darussalam": "n",
            "Tunisia": "n",
            "Sri Lanka": "n",
            "Mozambique": "n",
            "Bulgaria": "n",
            "New Zealand": "n",
            "Libya": "n",
            "Lebanon": "y",
            "Cote D'Ivoire": "n",
            "Ghana": "n",
            "Ukraine": "n",
            "Peru": "n",
            "Sweden": "n",
            "Gibraltar": "n",
            "Colombia": "n",
            "Argentina": "n",
            "Malta": "n",
            "Russia": "n"
        },
        {
            "GoodsName": "Prepared Foodstuffs",
            "Togo": "n",
            "Germany": "n",
            "Portugal": "n",
            "Hong Kong": "n",
            "Brunei Darussalam": "n",
            "Tunisia": "n",
            "Sri Lanka": "n",
            "Mozambique": "n",
            "Bulgaria": "n",
            "New Zealand": "n",
            "Libya": "y",
            "Lebanon": "y",
            "Cote D'Ivoire": "n",
            "Ghana": "n",
            "Ukraine": "n",
            "Peru": "n",
            "Sweden": "n",
            "Gibraltar": "n",
            "Colombia": "n",
            "Argentina": "n",
            "Malta": "n",
            "Russia": "n"
        },
        {
            "GoodsName": "Mineral products",
            "Togo": "n",
            "Germany": "y",
            "Portugal": "n",
            "Hong Kong": "n",
            "Brunei Darussalam": "n",
            "Tunisia": "n",
            "Sri Lanka": "y",
            "Mozambique": "y",
            "Bulgaria": "n",
            "New Zealand": "n",
            "Libya": "n",
            "Lebanon": "n",
            "Cote D'Ivoire": "y",
            "Ghana": "y",
            "Ukraine": "n",
            "Peru": "n",
            "Sweden": "n",
            "Gibraltar": "n",
            "Colombia": "n",
            "Argentina": "n",
            "Malta": "n",
            "Russia": "n"
        },
        {
            "GoodsName": "Chemical Products",
            "Togo": "n",
            "Germany": "y",
            "Portugal": "y",
            "Hong Kong": "y",
            "Brunei Darussalam": "n",
            "Tunisia": "y",
            "Sri Lanka": "y",
            "Mozambique": "y",
            "Bulgaria": "n",
            "New Zealand": "y",
            "Libya": "y",
            "Lebanon": "y",
            "Cote D'Ivoire": "n",
            "Ghana": "y",
            "Ukraine": "y",
            "Peru": "n",
            "Sweden": "n",
            "Gibraltar": "n",
            "Colombia": "y",
            "Argentina": "y",
            "Malta": "y",
            "Russia": "n"
        },
        {
            "GoodsName": "Plastics",
            "Togo": "y",
            "Germany": "y",
            "Portugal": "y",
            "Hong Kong": "y",
            "Brunei Darussalam": "n",
            "Tunisia": "y",
            "Sri Lanka": "y",
            "Mozambique": "y",
            "Bulgaria": "y",
            "New Zealand": "y",
            "Libya": "y",
            "Lebanon": "y",
            "Cote D'Ivoire": "y",
            "Ghana": "y",
            "Ukraine": "y",
            "Peru": "y",
            "Sweden": "y",
            "Gibraltar": "n",
            "Colombia": "y",
            "Argentina": "y",
            "Malta": "n",
            "Russia": "n"
        },
        {
            "GoodsName": "Raw Hide",
            "Togo": "n",
            "Germany": "n",
            "Portugal": "n",
            "Hong Kong": "n",
            "Brunei Darussalam": "n",
            "Tunisia": "n",
            "Sri Lanka": "n",
            "Mozambique": "n",
            "Bulgaria": "n",
            "New Zealand": "n",
            "Libya": "n",
            "Lebanon": "n",
            "Cote D'Ivoire": "n",
            "Ghana": "n",
            "Ukraine": "n",
            "Peru": "n",
            "Sweden": "n",
            "Gibraltar": "n",
            "Colombia": "n",
            "Argentina": "n",
            "Malta": "n",
            "Russia": "n"
        },
        {
            "GoodsName": "Wood",
            "Togo": "n",
            "Germany": "n",
            "Portugal": "n",
            "Hong Kong": "n",
            "Brunei Darussalam": "n",
            "Tunisia": "n",
            "Sri Lanka": "n",
            "Mozambique": "n",
            "Bulgaria": "n",
            "New Zealand": "n",
            "Libya": "n",
            "Lebanon": "n",
            "Cote D'Ivoire": "n",
            "Ghana": "n",
            "Ukraine": "n",
            "Peru": "n",
            "Sweden": "n",
            "Gibraltar": "n",
            "Colombia": "n",
            "Argentina": "n",
            "Malta": "n",
            "Russia": "n"
        },
        {
            "GoodsName": "Paper",
            "Togo": "n",
            "Germany": "n",
            "Portugal": "n",
            "Hong Kong": "n",
            "Brunei Darussalam": "n",
            "Tunisia": "n",
            "Sri Lanka": "y",
            "Mozambique": "n",
            "Bulgaria": "n",
            "New Zealand": "n",
            "Libya": "y",
            "Lebanon": "y",
            "Cote D'Ivoire": "n",
            "Ghana": "n",
            "Ukraine": "n",
            "Peru": "n",
            "Sweden": "n",
            "Gibraltar": "n",
            "Colombia": "n",
            "Argentina": "n",
            "Malta": "n",
            "Russia": "n"
        },
        {
            "GoodsName": "Textiles",
            "Togo": "n",
            "Germany": "y",
            "Portugal": "n",
            "Hong Kong": "n",
            "Brunei Darussalam": "n",
            "Tunisia": "y",
            "Sri Lanka": "n",
            "Mozambique": "n",
            "Bulgaria": "n",
            "New Zealand": "y",
            "Libya": "n",
            "Lebanon": "y",
            "Cote D'Ivoire": "n",
            "Ghana": "n",
            "Ukraine": "n",
            "Peru": "n",
            "Sweden": "n",
            "Gibraltar": "n",
            "Colombia": "n",
            "Argentina": "n",
            "Malta": "n",
            "Russia": "n"
        },
        {
            "GoodsName": "Footwear",
            "Togo": "n",
            "Germany": "n",
            "Portugal": "n",
            "Hong Kong": "n",
            "Brunei Darussalam": "n",
            "Tunisia": "n",
            "Sri Lanka": "n",
            "Mozambique": "n",
            "Bulgaria": "n",
            "New Zealand": "n",
            "Libya": "n",
            "Lebanon": "n",
            "Cote D'Ivoire": "n",
            "Ghana": "n",
            "Ukraine": "n",
            "Peru": "n",
            "Sweden": "n",
            "Gibraltar": "n",
            "Colombia": "n",
            "Argentina": "n",
            "Malta": "n",
            "Russia": "n"
        },
        {
            "GoodsName": "Construction",
            "Togo": "n",
            "Germany": "n",
            "Portugal": "n",
            "Hong Kong": "n",
            "Brunei Darussalam": "n",
            "Tunisia": "n",
            "Sri Lanka": "n",
            "Mozambique": "n",
            "Bulgaria": "n",
            "New Zealand": "y",
            "Libya": "n",
            "Lebanon": "y",
            "Cote D'Ivoire": "n",
            "Ghana": "n",
            "Ukraine": "n",
            "Peru": "n",
            "Sweden": "n",
            "Gibraltar": "n",
            "Colombia": "n",
            "Argentina": "n",
            "Malta": "n",
            "Russia": "n"
        },
        {
            "GoodsName": "Jewelery",
            "Togo": "n",
            "Germany": "y",
            "Portugal": "n",
            "Hong Kong": "n",
            "Brunei Darussalam": "n",
            "Tunisia": "n",
            "Sri Lanka": "n",
            "Mozambique": "n",
            "Bulgaria": "n",
            "New Zealand": "n",
            "Libya": "n",
            "Lebanon": "y",
            "Cote D'Ivoire": "n",
            "Ghana": "n",
            "Ukraine": "n",
            "Peru": "n",
            "Sweden": "y",
            "Gibraltar": "n",
            "Colombia": "n",
            "Argentina": "n",
            "Malta": "n",
            "Russia": "n"
        },
        {
            "GoodsName": "Base metals",
            "Togo": "n",
            "Germany": "y",
            "Portugal": "n",
            "Hong Kong": "y",
            "Brunei Darussalam": "n",
            "Tunisia": "y",
            "Sri Lanka": "n",
            "Mozambique": "n",
            "Bulgaria": "y",
            "New Zealand": "n",
            "Libya": "n",
            "Lebanon": "y",
            "Cote D'Ivoire": "n",
            "Ghana": "n",
            "Ukraine": "n",
            "Peru": "n",
            "Sweden": "n",
            "Gibraltar": "n",
            "Colombia": "y",
            "Argentina": "n",
            "Malta": "n",
            "Russia": "n"
        },
        {
            "GoodsName": "Machine",
            "Togo": "n",
            "Germany": "y",
            "Portugal": "n",
            "Hong Kong": "y",
            "Brunei Darussalam": "n",
            "Tunisia": "y",
            "Sri Lanka": "n",
            "Mozambique": "n",
            "Bulgaria": "y",
            "New Zealand": "n",
            "Libya": "y",
            "Lebanon": "n",
            "Cote D'Ivoire": "n",
            "Ghana": "n",
            "Ukraine": "y",
            "Peru": "n",
            "Sweden": "y",
            "Gibraltar": "n",
            "Colombia": "y",
            "Argentina": "n",
            "Malta": "n",
            "Russia": "n"
        },
        {
            "GoodsName": "Transport Equipment",
            "Togo": "n",
            "Germany": "y",
            "Portugal": "n",
            "Hong Kong": "y",
            "Brunei Darussalam": "n",
            "Tunisia": "y",
            "Sri Lanka": "n",
            "Mozambique": "n",
            "Bulgaria": "y",
            "New Zealand": "n",
            "Libya": "y",
            "Lebanon": "n",
            "Cote D'Ivoire": "n",
            "Ghana": "n",
            "Ukraine": "n",
            "Peru": "n",
            "Sweden": "y",
            "Gibraltar": "n",
            "Colombia": "n",
            "Argentina": "n",
            "Malta": "n",
            "Russia": "n"
        },
        {
            "GoodsName": "Optical",
            "Togo": "n",
            "Germany": "y",
            "Portugal": "n",
            "Hong Kong": "y",
            "Brunei Darussalam": "n",
            "Tunisia": "n",
            "Sri Lanka": "n",
            "Mozambique": "n",
            "Bulgaria": "n",
            "New Zealand": "n",
            "Libya": "n",
            "Lebanon": "n",
            "Cote D'Ivoire": "n",
            "Ghana": "n",
            "Ukraine": "n",
            "Peru": "n",
            "Sweden": "n",
            "Gibraltar": "n",
            "Colombia": "n",
            "Argentina": "n",
            "Malta": "n",
            "Russia": "n"
        },
        {
            "GoodsName": "Ammunition",
            "Togo": "n",
            "Germany": "n",
            "Portugal": "n",
            "Hong Kong": "n",
            "Brunei Darussalam": "n",
            "Tunisia": "n",
            "Sri Lanka": "n",
            "Mozambique": "n",
            "Bulgaria": "n",
            "New Zealand": "n",
            "Libya": "n",
            "Lebanon": "n",
            "Cote D'Ivoire": "n",
            "Ghana": "n",
            "Ukraine": "n",
            "Peru": "n",
            "Sweden": "n",
            "Gibraltar": "n",
            "Colombia": "n",
            "Argentina": "n",
            "Malta": "n",
            "Russia": "n"
        },
        {
            "GoodsName": "Mfd items",
            "Togo": "n",
            "Germany": "n",
            "Portugal": "n",
            "Hong Kong": "n",
            "Brunei Darussalam": "n",
            "Tunisia": "n",
            "Sri Lanka": "n",
            "Mozambique": "n",
            "Bulgaria": "n",
            "New Zealand": "n",
            "Libya": "n",
            "Lebanon": "n",
            "Cote D'Ivoire": "n",
            "Ghana": "n",
            "Ukraine": "n",
            "Peru": "n",
            "Sweden": "n",
            "Gibraltar": "n",
            "Colombia": "n",
            "Argentina": "n",
            "Malta": "n",
            "Russia": "n"
        },
        {
            "GoodsName": "Arts",
            "Togo": "n",
            "Germany": "n",
            "Portugal": "n",
            "Hong Kong": "n",
            "Brunei Darussalam": "n",
            "Tunisia": "n",
            "Sri Lanka": "n",
            "Mozambique": "n",
            "Bulgaria": "n",
            "New Zealand": "n",
            "Libya": "n",
            "Lebanon": "n",
            "Cote D'Ivoire": "n",
            "Ghana": "n",
            "Ukraine": "n",
            "Peru": "n",
            "Sweden": "n",
            "Gibraltar": "n",
            "Colombia": "n",
            "Argentina": "n",
            "Malta": "n",
            "Russia": "n"
        }
    ]
}